---
apiVersion: controlplane.cluster.x-k8s.io/{{ .Values.clusterapiVersion }}
kind: KubeadmControlPlane
metadata:
  name: {{ include "capi-openstack.kubeadmControlPlaneName" . }}
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/{{ .Values.clusterapiVersion }}
    kind: OpenStackMachineTemplate
    name: {{ include "capi-openstack.kubeadmControlPlaneName" . }}
  kubeadmConfigSpec:
    preKubeadmCommands:
    {{- if not (empty .Values.kubeadm.preKubeadmCommands) }}
    {{- range .Values.kubeadm.preKubeadmCommands }}
        - {{ . }}
    {{- end }}
    {{- end -}}
    clusterConfiguration:
    {{- toYaml ( required ".Values.kubeadm.clusterConfiguration"
        .Values.kubeadm.clusterConfiguration ) | nindent 6 }}
    initConfiguration:
    {{- toYaml (required ".Values.kubeadm.initConfiguration"
        .Values.kubeadm.initConfiguration ) | nindent 6 }}
    joinConfiguration:
    {{- toYaml (required ".Values.kubeadm.joinConfiguration"
        .Values.kubeadm.joinConfiguration ) | nindent 6 }}
  replicas: {{ default 1 .Values.kubernetes.mastersReplicas }}
  version: {{ required ".Values.kubernetes.version" .Values.kubernetes.version }}
