{{- if not .Values.cloudConfigSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: {{ printf "%s-cloud-config" .Values.name }}
data:
  cacert: {{ (.Values.cloudConfigSecret.caCert | default "\n") | b64enc }}
  clouds.yaml: {{ (required ".Values.cloudConfigSecret.clouds_yaml must be set"
        .Values.cloudConfigSecret.clouds_yaml ) | b64enc }}
{{- end -}}
