{{- if not .Values.cloudConfigSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: {{ include "capi-openstack.cloudConfigSecretName" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete
data:
  cacert: {{ (.Values.cloudConfigSecret.caCert | default "\n") | b64enc }}
  clouds.yaml: {{ (required ".Values.cloudConfigSecret.clouds_yaml must be set"
        .Values.cloudConfigSecret.clouds_yaml ) | b64enc }}
{{- end -}}
