apiVersion: addons.cluster.x-k8s.io/v1alpha3
kind: ClusterResourceSet
metadata:
  name: {{ include "capi-openstack.name" . }}
spec:
  clusterSelector:
    matchLabels:
      prueba: "true"
  resources:
  - kind: ConfigMap
    name: cni-calico
  strategy: ApplyOnce
