---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "capi-vsphere.crsCSIConfigName" . }}
stringData:
  data: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: {{ include "capi-vsphere.crsCSIConfigName" . }}
      namespace: kube-system
    stringData:
      csi-vsphere.conf: |+
        [Global]
        cluster-id = '{{ .Release.Namespace }}/{{ include "capi-vsphere.name" . }}'
        insecure-flag = {{ .Values.vsphere.insecure }}

        [VirtualCenter "{{ .Values.vsphere.server }}"]
        user = "{{ .Values.cloudConfigSecret.username }}"
        password = "{{ .Values.cloudConfigSecret.password }}"
        datacenters = "{{ .Values.vsphere.cloudProviderConfiguration.workspace.datacenter }}"

        [Network]
        public-network = "{{ .Values.vsphere.cloudProviderConfiguration.network.name }}"

    type: Opaque
type: addons.cluster.x-k8s.io/resource-set
