---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "capi-vsphere.crsCSIStorageClassName" . }}
data:
  sc.yaml: |+
    ---
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: csi-vsphere
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: csi.vsphere.vmware.com
    parameters:
      storagepolicyname: ""
      fstype: ext4

