{{- if not .Values.cloudConfigSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "capi-vsphere.cloudConfigSecretName" . }}
  annotations:
    "helm.sh/hook": pre-install
data:
  username: {{ .Values.cloudConfigSecret.username | b64enc }}
  password: {{ .Values.cloudConfigSecret.password | b64enc }}
{{- end -}}
