{{ range $crs := .Values.crsObjects }}
{{- $pattern := printf "files/crs/%s/*.yaml" $crs -}}
{{- $crsName := printf "%s-%s" (include "capi-vsphere.name" $) $crs | trunc 63 | trimSuffix "-" -}}
{{ if ($.Files.Glob $pattern ) }}
---
apiVersion: addons.cluster.x-k8s.io/{{ $.Values.clusterapiVersion }}
kind: ClusterResourceSet
metadata:
  name: {{ $crsName }}
spec:
  clusterSelector:
    matchLabels:
      {{ $crsName }}: "true"
  resources:
  - kind: ConfigMap
    name: {{ $crsName }}
  strategy: ApplyOnce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $crsName }}
data:
  {{ ($.Files.Glob $pattern).AsConfig | nindent 2 }}
{{ end }}
{{ end }}
