---
apiVersion: cluster.x-k8s.io/{{ .Values.clusterapiVersion }}
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ include "capi-vsphere.name" . }}
    {{ include "capi-vsphere.crsCloudConfigName" . }}: "true"
{{ range $crs := .Values.crsObjects }}
{{- $crsName := printf "%s-%s" (include "capi-vsphere.name" $) $crs | trunc 63 | trimSuffix "-" }}
    {{ $crsName }}: "true"
{{ end }}
  name: {{ include "capi-vsphere.name" . }}
spec:
  clusterNetwork: {{ toYaml .Values.clusterNetwork | nindent 4 }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/{{ .Values.clusterapiVersion }}
    kind: KubeadmControlPlane
    name: {{ include "capi-vsphere.kubeadmControlPlaneName" . }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/{{ .Values.clusterapiVersion }}
    kind: VSphereCluster
    name: {{ include "capi-vsphere.name" . }}
