{{- $cloudConfigSecret := include "capi-vsphere.cloudConfigSecret" .  -}}
apiVersion: infrastructure.cluster.x-k8s.io/{{ .Values.clusterapiVersion }}
kind: VSphereMachineTemplate
metadata:
  name: {{ include "capi-vsphere.kubeadmControlPlaneName" . }}
spec:
  template:
    spec:
      {{- with .Values.controlPlaneTemplate.cloneMode }}
      cloneMode: {{ . }}
      {{- end }}
      {{- with .Values.controlPlaneTemplate.customVMXKeys }}
      customVMXKeys: {{ toYaml . | nindent 8 }}
      {{- end }}
      datacenter: {{ default .Values.vsphere.cloudProviderConfiguration.workspace.datacenter .Values.controlPlaneTemplate.datacenter }}
      datastore: {{ default .Values.vsphere.cloudProviderConfiguration.workspace.datastore .Values.controlPlaneTemplate.datastore }}
      {{- with .Values.controlPlaneTemplate.diskGiB }}
      diskGiB: {{ . }}
      {{- end }}
      {{- with .Values.controlPlaneTemplate.failureDomain }}
      failureDomain: {{ . }}
      {{- end }}
      folder: {{ default .Values.vsphere.cloudProviderConfiguration.workspace.folder .Values.controlPlaneTemplate.folder }}
      {{- with .Values.controlPlaneTemplate.memoryMiB }}
      memoryMiB: {{ . }}
      {{- end }}
      network: {{ toYaml (required ".Values.controlPlaneTemplate.network is required" .Values.controlPlaneTemplate.network) | nindent 8 }}
      {{- with .Values.controlPlaneTemplate.numCPUs }}
      numCPUs: {{ . }}
      {{- end }}
      {{- with .Values.controlPlaneTemplate.numCoresPerSocket }}
      numCoresPerSocket: {{ . }}
      {{- end }}
      {{- with .Values.controlPlaneTemplate.providerID }}
      providerID: {{ . }}
      {{- end }}
      resourcePool: {{ default .Values.vsphere.cloudProviderConfiguration.workspace.resourcePool .Values.controlPlaneTemplate.resourcePool }}
      server: {{ default .Values.vsphere.server .Values.controlPlaneTemplate.server }}
      {{- with .Values.controlPlaneTemplate.snapshot }}
      snapshot: {{ . }}
      {{- end }}
      {{- with .Values.controlPlaneTemplate.storagePolicyName }}
      storagePolicyName: {{ . }}
      {{- end }}
      template: {{ required ".Values.controlPlaneTemplate.template is required" .Values.controlPlaneTemplate.template }}
      thumbprint: {{ default .Values.vsphere.thumbprint .Values.controlPlaneTemplate.thumbprint }}
{{ range $index, $template := .Values.machineTemplates }}
{{- $object := dict "MachineTemplate" $template "Index" $index "Context" $ -}}
---
apiVersion: infrastructure.cluster.x-k8s.io/{{ $.Values.clusterapiVersion }}
kind: VSphereMachineTemplate
metadata:
  name: {{ include "capi-vsphere.machineTemplateName" $object }}
spec:
  template:
    spec:
      {{- with $template.cloneMode }}
      cloneMode: {{ . }}
      {{- end }}
      {{- with $template.customVMXKeys }}
      customVMXKeys: {{ toYaml . | nindent 8 }}
      {{- end }}
      datacenter: {{ default $.Values.vsphere.cloudProviderConfiguration.workspace.datacenter $template.datacenter }}
      datastore: {{ default $.Values.vsphere.cloudProviderConfiguration.workspace.datastore $template.datastore }}
      {{- with $template.diskGiB }}
      diskGiB: {{ . }}
      {{- end }}
      {{- with $template.failureDomain }}
      failureDomain: {{ . }}
      {{- end }}
      folder: {{ default $.Values.vsphere.cloudProviderConfiguration.workspace.folder $template.folder }}
      {{- with $template.memoryMiB }}
      memoryMiB: {{ . }}
      {{- end }}
      network: {{ toYaml (required (printf ".Values.machineTemplates[%d].network is required" $index) $template.network) | nindent 8 }}
      {{- with $template.numCPUs }}
      numCPUs: {{ . }}
      {{- end }}
      {{- with $template.numCoresPerSocket }}
      numCoresPerSocket: {{ . }}
      {{- end }}
      {{- with $template.providerID }}
      providerID: {{ . }}
      {{- end }}
      resourcePool: {{ default $.Values.vsphere.cloudProviderConfiguration.workspace.resourcePool $template.resourcePool }}
      server: {{ default $.Values.vsphere.server $template.server }}
      {{- with $template.snapshot }}
      snapshot: {{ . }}
      {{- end }}
      {{- with $template.storagePolicyName }}
      storagePolicyName: {{ . }}
      {{- end }}
      template: {{ required (printf ".Values.machineTemplates[%d].template is required" $index) $template.template }}
      thumbprint: {{ default $.Values.vsphere.thumbprint $template.thumbprint }}
{{ end }}
